### ISSUE TITLE
Error pulling from CocoaPods

### ISSUE THREAD

**Issue by thibmaek** [Ramotion/paper-onboarding#4]
### Command

```
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/bin/pod install
```
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.8.2
Ruby lib dir : /Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7081552c485f434e1f704140a64429136ab329d8
```
### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```
### Podfile

``` ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Turntablism' do

pod 'paper-onboarding'

end
```
### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="paper-onboarding">
Did you mean?  to_query
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/bin/pod:22:in `load'
/Users/thibaultmaekelbergh/.rbenv/versions/2.3.1/bin/pod:22:in `<main>'
```

**Comment by ardavank** [comment]
@thibmaek 
put `pod 'paper-onboarding'` under  `use_frameworks!` instead of `target 'Turntablism' do`
